bsub -J MCSmearHighR9EEPhi -o out_MCSmearHighR9EEPhi -q 1nh run_MCSmearHighR9EEPhi.sh
bsub -J MCScaleHighR9EB -o out_MCScaleHighR9EB -q 1nh run_MCScaleHighR9EB.sh
bsub -J MCScaleHighR9EE -o out_MCScaleHighR9EE -q 1nh run_MCScaleHighR9EE.sh
bsub -J MCSmearLowR9EERho -o out_MCSmearLowR9EERho -q 1nh run_MCSmearLowR9EERho.sh
bsub -J MCSmearHighR9EERho -o out_MCSmearHighR9EERho -q 1nh run_MCSmearHighR9EERho.sh
bsub -J MCSmearHighR9EBRho -o out_MCSmearHighR9EBRho -q 1nh run_MCSmearHighR9EBRho.sh
bsub -J FNUFEE -o out_FNUFEE -q 1nh run_FNUFEE.sh
bsub -J ShowerShapeHighR9EB -o out_ShowerShapeHighR9EB -q 1nh run_ShowerShapeHighR9EB.sh
bsub -J MaterialOuterBarrel -o out_MaterialOuterBarrel -q 1nh run_MaterialOuterBarrel.sh
bsub -J MCScaleLowR9EE -o out_MCScaleLowR9EE -q 1nh run_MCScaleLowR9EE.sh
bsub -J FNUFEB -o out_FNUFEB -q 1nh run_FNUFEB.sh
bsub -J MCScaleGain6EB -o out_MCScaleGain6EB -q 1nh run_MCScaleGain6EB.sh
bsub -J MCSmearLowR9EBRho -o out_MCSmearLowR9EBRho -q 1nh run_MCSmearLowR9EBRho.sh
bsub -J MCSmearLowR9EBPhi -o out_MCSmearLowR9EBPhi -q 1nh run_MCSmearLowR9EBPhi.sh
bsub -J MCScaleLowR9EB -o out_MCScaleLowR9EB -q 1nh run_MCScaleLowR9EB.sh
bsub -J MCSmearHighR9EBPhi -o out_MCSmearHighR9EBPhi -q 1nh run_MCSmearHighR9EBPhi.sh
bsub -J ShowerShapeLowR9EE -o out_ShowerShapeLowR9EE -q 1nh run_ShowerShapeLowR9EE.sh
bsub -J MCScaleGain1EB -o out_MCScaleGain1EB -q 1nh run_MCScaleGain1EB.sh
bsub -J MaterialForward -o out_MaterialForward -q 1nh run_MaterialForward.sh
bsub -J MaterialCentralBarrel -o out_MaterialCentralBarrel -q 1nh run_MaterialCentralBarrel.sh
