void CRInvertLepCut_mGG_canvas()
{
//=========Macro generated from canvas: CRInvertLepCut_mGG_canvas/
//=========  (Mon Jul 24 13:06:21 2017) by ROOT version6.08/00

   gStyle->SetCanvasPreferGL(kTRUE);

   TCanvas *CRInvertLepCut_mGG_canvas = new TCanvas("CRInvertLepCut_mGG_canvas", "",49,24,1696,1056);
   CRInvertLepCut_mGG_canvas->SetHighLightColor(2);
   CRInvertLepCut_mGG_canvas->Range(0,0,1,1);
   CRInvertLepCut_mGG_canvas->SetFillColor(0);
   CRInvertLepCut_mGG_canvas->SetBorderMode(0);
   CRInvertLepCut_mGG_canvas->SetBorderSize(2);
   CRInvertLepCut_mGG_canvas->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: CRInvertLepCut_mGG_pad1
   TPad *CRInvertLepCut_mGG_pad1 = new TPad("CRInvertLepCut_mGG_pad1", "CRInvertLepCut_mGG_pad1",0,0.25,1,1);
   CRInvertLepCut_mGG_pad1->Draw();
   CRInvertLepCut_mGG_pad1->cd();
   CRInvertLepCut_mGG_pad1->Range(90,-4.905987,190,5.898578);
   CRInvertLepCut_mGG_pad1->SetFillColor(0);
   CRInvertLepCut_mGG_pad1->SetBorderMode(0);
   CRInvertLepCut_mGG_pad1->SetBorderSize(2);
   CRInvertLepCut_mGG_pad1->SetLogy();
   CRInvertLepCut_mGG_pad1->SetFrameBorderMode(0);
   CRInvertLepCut_mGG_pad1->SetFrameBorderMode(0);
   
   TH1F *CRInvertLepCut_mGG_Data__1 = new TH1F("CRInvertLepCut_mGG_Data__1","Inverted Lepton selection Control Region",8,100,180);
   CRInvertLepCut_mGG_Data__1->SetBinContent(1,38);
   CRInvertLepCut_mGG_Data__1->SetBinContent(2,19);
   CRInvertLepCut_mGG_Data__1->SetBinContent(3,27);
   CRInvertLepCut_mGG_Data__1->SetBinContent(4,20);
   CRInvertLepCut_mGG_Data__1->SetBinContent(5,15);
   CRInvertLepCut_mGG_Data__1->SetBinContent(6,5);
   CRInvertLepCut_mGG_Data__1->SetBinContent(7,10);
   CRInvertLepCut_mGG_Data__1->SetBinContent(8,6);
   CRInvertLepCut_mGG_Data__1->SetBinError(1,6.164414);
   CRInvertLepCut_mGG_Data__1->SetBinError(2,4.358899);
   CRInvertLepCut_mGG_Data__1->SetBinError(3,5.196152);
   CRInvertLepCut_mGG_Data__1->SetBinError(4,4.472136);
   CRInvertLepCut_mGG_Data__1->SetBinError(5,3.872983);
   CRInvertLepCut_mGG_Data__1->SetBinError(6,2.236068);
   CRInvertLepCut_mGG_Data__1->SetBinError(7,3.162278);
   CRInvertLepCut_mGG_Data__1->SetBinError(8,2.44949);
   CRInvertLepCut_mGG_Data__1->SetMinimum(0.000149441);
   CRInvertLepCut_mGG_Data__1->SetMaximum(65784.21);
   CRInvertLepCut_mGG_Data__1->SetEntries(140);
   CRInvertLepCut_mGG_Data__1->SetDirectory(0);
   CRInvertLepCut_mGG_Data__1->SetStats(0);
   CRInvertLepCut_mGG_Data__1->SetLineWidth(2);
   CRInvertLepCut_mGG_Data__1->SetMarkerStyle(20);
   CRInvertLepCut_mGG_Data__1->GetXaxis()->SetTitle("#gamma#gamma invariant mass (GeV)");
   CRInvertLepCut_mGG_Data__1->GetXaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_Data__1->GetXaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_Data__1->GetXaxis()->SetTitleSize(0.05);
   CRInvertLepCut_mGG_Data__1->GetXaxis()->SetTitleOffset(0.95);
   CRInvertLepCut_mGG_Data__1->GetXaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_Data__1->GetYaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_Data__1->GetYaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_Data__1->GetYaxis()->SetTitleSize(0.07);
   CRInvertLepCut_mGG_Data__1->GetYaxis()->SetTitleOffset(0.72);
   CRInvertLepCut_mGG_Data__1->GetYaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_Data__1->GetZaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_Data__1->GetZaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_Data__1->GetZaxis()->SetTitleSize(0.035);
   CRInvertLepCut_mGG_Data__1->GetZaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_Data__1->Draw("E");
   
   THStack *CRInvertLepCut_mGG_stack = new THStack();
   CRInvertLepCut_mGG_stack->SetName("CRInvertLepCut_mGG_stack");
   CRInvertLepCut_mGG_stack->SetTitle("CRInvertLepCut_mGG");
   
   TH1F *CRInvertLepCut_mGG_stack_stack_1 = new TH1F("CRInvertLepCut_mGG_stack_stack_1","CRInvertLepCut_mGG",8,100,180);
   CRInvertLepCut_mGG_stack_stack_1->SetMinimum(0.01709752);
   CRInvertLepCut_mGG_stack_stack_1->SetMaximum(68.39009);
   CRInvertLepCut_mGG_stack_stack_1->SetDirectory(0);
   CRInvertLepCut_mGG_stack_stack_1->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   CRInvertLepCut_mGG_stack_stack_1->SetLineColor(ci);
   CRInvertLepCut_mGG_stack_stack_1->GetXaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_stack_stack_1->GetXaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_stack_stack_1->GetXaxis()->SetTitleSize(0.035);
   CRInvertLepCut_mGG_stack_stack_1->GetXaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_stack_stack_1->GetYaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_stack_stack_1->GetYaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_stack_stack_1->GetYaxis()->SetTitleSize(0.035);
   CRInvertLepCut_mGG_stack_stack_1->GetYaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_stack_stack_1->GetZaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_stack_stack_1->GetZaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_stack_stack_1->GetZaxis()->SetTitleSize(0.035);
   CRInvertLepCut_mGG_stack_stack_1->GetZaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_stack->SetHistogram(CRInvertLepCut_mGG_stack_stack_1);
   
   
   TH1F *CRInvertLepCut_mGG_tHq__2 = new TH1F("CRInvertLepCut_mGG_tHq__2","cCRInvertLepCut",8,100,180);
   CRInvertLepCut_mGG_tHq__2->SetBinContent(1,0.0002031349);
   CRInvertLepCut_mGG_tHq__2->SetBinContent(2,0.001824946);
   CRInvertLepCut_mGG_tHq__2->SetBinContent(3,0.04960788);
   CRInvertLepCut_mGG_tHq__2->SetBinContent(4,0.0003326013);
   CRInvertLepCut_mGG_tHq__2->SetBinContent(5,2.315912e-05);
   CRInvertLepCut_mGG_tHq__2->SetBinContent(6,3.904855e-05);
   CRInvertLepCut_mGG_tHq__2->SetBinContent(7,3.287519e-05);
   CRInvertLepCut_mGG_tHq__2->SetBinContent(8,3.849188e-05);
   CRInvertLepCut_mGG_tHq__2->SetBinError(1,2.747395e-05);
   CRInvertLepCut_mGG_tHq__2->SetBinError(2,7.940989e-05);
   CRInvertLepCut_mGG_tHq__2->SetBinError(3,0.0004158218);
   CRInvertLepCut_mGG_tHq__2->SetBinError(4,3.349737e-05);
   CRInvertLepCut_mGG_tHq__2->SetBinError(5,9.500654e-06);
   CRInvertLepCut_mGG_tHq__2->SetBinError(6,1.196663e-05);
   CRInvertLepCut_mGG_tHq__2->SetBinError(7,1.061696e-05);
   CRInvertLepCut_mGG_tHq__2->SetBinError(8,1.246699e-05);
   CRInvertLepCut_mGG_tHq__2->SetEntries(16422);
   CRInvertLepCut_mGG_tHq__2->SetDirectory(0);

   ci = TColor::GetColor("#003333");
   CRInvertLepCut_mGG_tHq__2->SetFillColor(ci);

   ci = TColor::GetColor("#003333");
   CRInvertLepCut_mGG_tHq__2->SetLineColor(ci);
   CRInvertLepCut_mGG_tHq__2->SetLineStyle(2);
   CRInvertLepCut_mGG_tHq__2->SetLineWidth(2);
   CRInvertLepCut_mGG_tHq__2->GetXaxis()->SetTitle("#gamma#gamma invariant mass (GeV)");
   CRInvertLepCut_mGG_tHq__2->GetXaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_tHq__2->GetXaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_tHq__2->GetXaxis()->SetTitleSize(0.035);
   CRInvertLepCut_mGG_tHq__2->GetXaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_tHq__2->GetYaxis()->SetTitle("#entries");
   CRInvertLepCut_mGG_tHq__2->GetYaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_tHq__2->GetYaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_tHq__2->GetYaxis()->SetTitleSize(0.035);
   CRInvertLepCut_mGG_tHq__2->GetYaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_tHq__2->GetZaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_tHq__2->GetZaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_tHq__2->GetZaxis()->SetTitleSize(0.035);
   CRInvertLepCut_mGG_tHq__2->GetZaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_stack->Add(CRInvertLepCut_mGG_tHq,"");
   
   TH1F *CRInvertLepCut_mGG_ttHpLtHW__3 = new TH1F("CRInvertLepCut_mGG_ttHpLtHW__3","cCRInvertLepCut",8,100,180);
   CRInvertLepCut_mGG_ttHpLtHW__3->SetBinContent(1,0.00358833);
   CRInvertLepCut_mGG_ttHpLtHW__3->SetBinContent(2,0.02595575);
   CRInvertLepCut_mGG_ttHpLtHW__3->SetBinContent(3,0.7161028);
   CRInvertLepCut_mGG_ttHpLtHW__3->SetBinContent(4,0.006896711);
   CRInvertLepCut_mGG_ttHpLtHW__3->SetBinContent(5,0.0009729178);
   CRInvertLepCut_mGG_ttHpLtHW__3->SetBinContent(6,0.001237067);
   CRInvertLepCut_mGG_ttHpLtHW__3->SetBinContent(7,0.0007193079);
   CRInvertLepCut_mGG_ttHpLtHW__3->SetBinContent(8,0.000678497);
   CRInvertLepCut_mGG_ttHpLtHW__3->SetBinError(1,0.000490245);
   CRInvertLepCut_mGG_ttHpLtHW__3->SetBinError(2,0.001324342);
   CRInvertLepCut_mGG_ttHpLtHW__3->SetBinError(3,0.00687641);
   CRInvertLepCut_mGG_ttHpLtHW__3->SetBinError(4,0.0007074756);
   CRInvertLepCut_mGG_ttHpLtHW__3->SetBinError(5,0.0002580774);
   CRInvertLepCut_mGG_ttHpLtHW__3->SetBinError(6,0.0003099896);
   CRInvertLepCut_mGG_ttHpLtHW__3->SetBinError(7,0.0002241048);
   CRInvertLepCut_mGG_ttHpLtHW__3->SetBinError(8,0.0002431937);
   CRInvertLepCut_mGG_ttHpLtHW__3->SetEntries(32276);
   CRInvertLepCut_mGG_ttHpLtHW__3->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   CRInvertLepCut_mGG_ttHpLtHW__3->SetFillColor(ci);

   ci = TColor::GetColor("#ff0000");
   CRInvertLepCut_mGG_ttHpLtHW__3->SetLineColor(ci);
   CRInvertLepCut_mGG_ttHpLtHW__3->SetLineStyle(2);
   CRInvertLepCut_mGG_ttHpLtHW__3->SetLineWidth(2);
   CRInvertLepCut_mGG_ttHpLtHW__3->GetXaxis()->SetTitle("#gamma#gamma invariant mass (GeV)");
   CRInvertLepCut_mGG_ttHpLtHW__3->GetXaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_ttHpLtHW__3->GetXaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_ttHpLtHW__3->GetXaxis()->SetTitleSize(0.035);
   CRInvertLepCut_mGG_ttHpLtHW__3->GetXaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_ttHpLtHW__3->GetYaxis()->SetTitle("#entries");
   CRInvertLepCut_mGG_ttHpLtHW__3->GetYaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_ttHpLtHW__3->GetYaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_ttHpLtHW__3->GetYaxis()->SetTitleSize(0.035);
   CRInvertLepCut_mGG_ttHpLtHW__3->GetYaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_ttHpLtHW__3->GetZaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_ttHpLtHW__3->GetZaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_ttHpLtHW__3->GetZaxis()->SetTitleSize(0.035);
   CRInvertLepCut_mGG_ttHpLtHW__3->GetZaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_stack->Add(CRInvertLepCut_mGG_ttH+tHW,"");
   
   TH1F *CRInvertLepCut_mGG_OtherHiggs__4 = new TH1F("CRInvertLepCut_mGG_OtherHiggs__4","cCRInvertLepCut",8,100,180);
   CRInvertLepCut_mGG_OtherHiggs__4->SetBinContent(2,0.02312028);
   CRInvertLepCut_mGG_OtherHiggs__4->SetBinContent(3,0.3404502);
   CRInvertLepCut_mGG_OtherHiggs__4->SetBinContent(4,0.009129228);
   CRInvertLepCut_mGG_OtherHiggs__4->SetBinError(2,0.01402962);
   CRInvertLepCut_mGG_OtherHiggs__4->SetBinError(3,0.07707955);
   CRInvertLepCut_mGG_OtherHiggs__4->SetBinError(4,0.007872299);
   CRInvertLepCut_mGG_OtherHiggs__4->SetEntries(384);
   CRInvertLepCut_mGG_OtherHiggs__4->SetDirectory(0);

   ci = TColor::GetColor("#0000ff");
   CRInvertLepCut_mGG_OtherHiggs__4->SetFillColor(ci);

   ci = TColor::GetColor("#0000ff");
   CRInvertLepCut_mGG_OtherHiggs__4->SetLineColor(ci);
   CRInvertLepCut_mGG_OtherHiggs__4->SetLineStyle(2);
   CRInvertLepCut_mGG_OtherHiggs__4->SetLineWidth(2);
   CRInvertLepCut_mGG_OtherHiggs__4->GetXaxis()->SetTitle("#gamma#gamma invariant mass (GeV)");
   CRInvertLepCut_mGG_OtherHiggs__4->GetXaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_OtherHiggs__4->GetXaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_OtherHiggs__4->GetXaxis()->SetTitleSize(0.035);
   CRInvertLepCut_mGG_OtherHiggs__4->GetXaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_OtherHiggs__4->GetYaxis()->SetTitle("#entries");
   CRInvertLepCut_mGG_OtherHiggs__4->GetYaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_OtherHiggs__4->GetYaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_OtherHiggs__4->GetYaxis()->SetTitleSize(0.035);
   CRInvertLepCut_mGG_OtherHiggs__4->GetYaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_OtherHiggs__4->GetZaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_OtherHiggs__4->GetZaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_OtherHiggs__4->GetZaxis()->SetTitleSize(0.035);
   CRInvertLepCut_mGG_OtherHiggs__4->GetZaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_stack->Add(CRInvertLepCut_mGG_OtherHiggs,"");
   
   TH1F *CRInvertLepCut_mGG_VectorBosons__5 = new TH1F("CRInvertLepCut_mGG_VectorBosons__5","cCRInvertLepCut",8,100,180);
   CRInvertLepCut_mGG_VectorBosons__5->SetBinContent(1,0.4862546);
   CRInvertLepCut_mGG_VectorBosons__5->SetBinContent(3,2.696861);
   CRInvertLepCut_mGG_VectorBosons__5->SetBinContent(5,0.4559445);
   CRInvertLepCut_mGG_VectorBosons__5->SetBinContent(6,0.04447453);
   CRInvertLepCut_mGG_VectorBosons__5->SetBinError(1,0.4862546);
   CRInvertLepCut_mGG_VectorBosons__5->SetBinError(3,2.831855);
   CRInvertLepCut_mGG_VectorBosons__5->SetBinError(5,0.4559445);
   CRInvertLepCut_mGG_VectorBosons__5->SetBinError(6,0.04447453);
   CRInvertLepCut_mGG_VectorBosons__5->SetEntries(7);
   CRInvertLepCut_mGG_VectorBosons__5->SetDirectory(0);

   ci = TColor::GetColor("#009900");
   CRInvertLepCut_mGG_VectorBosons__5->SetFillColor(ci);

   ci = TColor::GetColor("#009900");
   CRInvertLepCut_mGG_VectorBosons__5->SetLineColor(ci);
   CRInvertLepCut_mGG_VectorBosons__5->SetLineStyle(2);
   CRInvertLepCut_mGG_VectorBosons__5->SetLineWidth(2);
   CRInvertLepCut_mGG_VectorBosons__5->GetXaxis()->SetTitle("#gamma#gamma invariant mass (GeV)");
   CRInvertLepCut_mGG_VectorBosons__5->GetXaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_VectorBosons__5->GetXaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_VectorBosons__5->GetXaxis()->SetTitleSize(0.035);
   CRInvertLepCut_mGG_VectorBosons__5->GetXaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_VectorBosons__5->GetYaxis()->SetTitle("#entries");
   CRInvertLepCut_mGG_VectorBosons__5->GetYaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_VectorBosons__5->GetYaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_VectorBosons__5->GetYaxis()->SetTitleSize(0.035);
   CRInvertLepCut_mGG_VectorBosons__5->GetYaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_VectorBosons__5->GetZaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_VectorBosons__5->GetZaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_VectorBosons__5->GetZaxis()->SetTitleSize(0.035);
   CRInvertLepCut_mGG_VectorBosons__5->GetZaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_stack->Add(CRInvertLepCut_mGG_VectorBosons,"");
   
   TH1F *CRInvertLepCut_mGG_Photons__6 = new TH1F("CRInvertLepCut_mGG_Photons__6","cCRInvertLepCut",8,100,180);
   CRInvertLepCut_mGG_Photons__6->SetBinContent(1,23.24057);
   CRInvertLepCut_mGG_Photons__6->SetBinContent(2,17.48894);
   CRInvertLepCut_mGG_Photons__6->SetBinContent(3,17.90626);
   CRInvertLepCut_mGG_Photons__6->SetBinContent(4,16.97113);
   CRInvertLepCut_mGG_Photons__6->SetBinContent(5,8.165257);
   CRInvertLepCut_mGG_Photons__6->SetBinContent(6,6.035398);
   CRInvertLepCut_mGG_Photons__6->SetBinContent(7,5.296037);
   CRInvertLepCut_mGG_Photons__6->SetBinContent(8,6.927935);
   CRInvertLepCut_mGG_Photons__6->SetBinError(1,3.594);
   CRInvertLepCut_mGG_Photons__6->SetBinError(2,3.116667);
   CRInvertLepCut_mGG_Photons__6->SetBinError(3,3.008482);
   CRInvertLepCut_mGG_Photons__6->SetBinError(4,2.715765);
   CRInvertLepCut_mGG_Photons__6->SetBinError(5,2.338198);
   CRInvertLepCut_mGG_Photons__6->SetBinError(6,1.861175);
   CRInvertLepCut_mGG_Photons__6->SetBinError(7,1.714978);
   CRInvertLepCut_mGG_Photons__6->SetBinError(8,1.857863);
   CRInvertLepCut_mGG_Photons__6->SetEntries(855);
   CRInvertLepCut_mGG_Photons__6->SetDirectory(0);

   ci = TColor::GetColor("#ffcc00");
   CRInvertLepCut_mGG_Photons__6->SetFillColor(ci);

   ci = TColor::GetColor("#ffcc00");
   CRInvertLepCut_mGG_Photons__6->SetLineColor(ci);
   CRInvertLepCut_mGG_Photons__6->SetLineStyle(2);
   CRInvertLepCut_mGG_Photons__6->SetLineWidth(2);
   CRInvertLepCut_mGG_Photons__6->GetXaxis()->SetTitle("#gamma#gamma invariant mass (GeV)");
   CRInvertLepCut_mGG_Photons__6->GetXaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_Photons__6->GetXaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_Photons__6->GetXaxis()->SetTitleSize(0.035);
   CRInvertLepCut_mGG_Photons__6->GetXaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_Photons__6->GetYaxis()->SetTitle("#entries");
   CRInvertLepCut_mGG_Photons__6->GetYaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_Photons__6->GetYaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_Photons__6->GetYaxis()->SetTitleSize(0.035);
   CRInvertLepCut_mGG_Photons__6->GetYaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_Photons__6->GetZaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_Photons__6->GetZaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_Photons__6->GetZaxis()->SetTitleSize(0.035);
   CRInvertLepCut_mGG_Photons__6->GetZaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_stack->Add(CRInvertLepCut_mGG_Photons,"");
   
   TH1F *CRInvertLepCut_mGG_Top__7 = new TH1F("CRInvertLepCut_mGG_Top__7","cCRInvertLepCut",8,100,180);
   CRInvertLepCut_mGG_Top__7->SetBinContent(1,19.01319);
   CRInvertLepCut_mGG_Top__7->SetBinContent(2,6.328259);
   CRInvertLepCut_mGG_Top__7->SetBinContent(3,4.52484);
   CRInvertLepCut_mGG_Top__7->SetBinContent(5,1.626676);
   CRInvertLepCut_mGG_Top__7->SetBinContent(7,3.73425);
   CRInvertLepCut_mGG_Top__7->SetBinContent(8,9.026477);
   CRInvertLepCut_mGG_Top__7->SetBinError(1,7.136294);
   CRInvertLepCut_mGG_Top__7->SetBinError(2,3.983655);
   CRInvertLepCut_mGG_Top__7->SetBinError(3,3.211814);
   CRInvertLepCut_mGG_Top__7->SetBinError(5,1.626676);
   CRInvertLepCut_mGG_Top__7->SetBinError(7,4.371767);
   CRInvertLepCut_mGG_Top__7->SetBinError(8,4.773785);
   CRInvertLepCut_mGG_Top__7->SetEntries(22);
   CRInvertLepCut_mGG_Top__7->SetDirectory(0);

   ci = TColor::GetColor("#993333");
   CRInvertLepCut_mGG_Top__7->SetFillColor(ci);

   ci = TColor::GetColor("#993333");
   CRInvertLepCut_mGG_Top__7->SetLineColor(ci);
   CRInvertLepCut_mGG_Top__7->SetLineStyle(2);
   CRInvertLepCut_mGG_Top__7->SetLineWidth(2);
   CRInvertLepCut_mGG_Top__7->GetXaxis()->SetTitle("#gamma#gamma invariant mass (GeV)");
   CRInvertLepCut_mGG_Top__7->GetXaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_Top__7->GetXaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_Top__7->GetXaxis()->SetTitleSize(0.035);
   CRInvertLepCut_mGG_Top__7->GetXaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_Top__7->GetYaxis()->SetTitle("#entries");
   CRInvertLepCut_mGG_Top__7->GetYaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_Top__7->GetYaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_Top__7->GetYaxis()->SetTitleSize(0.035);
   CRInvertLepCut_mGG_Top__7->GetYaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_Top__7->GetZaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_Top__7->GetZaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_Top__7->GetZaxis()->SetTitleSize(0.035);
   CRInvertLepCut_mGG_Top__7->GetZaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_stack->Add(CRInvertLepCut_mGG_Top,"");
   CRInvertLepCut_mGG_stack->Draw("hist same");
   
   TH1F *CRInvertLepCut_mGG_Data__8 = new TH1F("CRInvertLepCut_mGG_Data__8","Inverted Lepton selection Control Region",8,100,180);
   CRInvertLepCut_mGG_Data__8->SetBinContent(1,38);
   CRInvertLepCut_mGG_Data__8->SetBinContent(2,19);
   CRInvertLepCut_mGG_Data__8->SetBinContent(3,27);
   CRInvertLepCut_mGG_Data__8->SetBinContent(4,20);
   CRInvertLepCut_mGG_Data__8->SetBinContent(5,15);
   CRInvertLepCut_mGG_Data__8->SetBinContent(6,5);
   CRInvertLepCut_mGG_Data__8->SetBinContent(7,10);
   CRInvertLepCut_mGG_Data__8->SetBinContent(8,6);
   CRInvertLepCut_mGG_Data__8->SetBinError(1,6.164414);
   CRInvertLepCut_mGG_Data__8->SetBinError(2,4.358899);
   CRInvertLepCut_mGG_Data__8->SetBinError(3,5.196152);
   CRInvertLepCut_mGG_Data__8->SetBinError(4,4.472136);
   CRInvertLepCut_mGG_Data__8->SetBinError(5,3.872983);
   CRInvertLepCut_mGG_Data__8->SetBinError(6,2.236068);
   CRInvertLepCut_mGG_Data__8->SetBinError(7,3.162278);
   CRInvertLepCut_mGG_Data__8->SetBinError(8,2.44949);
   CRInvertLepCut_mGG_Data__8->SetMinimum(0.000149441);
   CRInvertLepCut_mGG_Data__8->SetMaximum(65784.21);
   CRInvertLepCut_mGG_Data__8->SetEntries(140);
   CRInvertLepCut_mGG_Data__8->SetDirectory(0);
   CRInvertLepCut_mGG_Data__8->SetStats(0);
   CRInvertLepCut_mGG_Data__8->SetLineWidth(2);
   CRInvertLepCut_mGG_Data__8->SetMarkerStyle(20);
   CRInvertLepCut_mGG_Data__8->GetXaxis()->SetTitle("#gamma#gamma invariant mass (GeV)");
   CRInvertLepCut_mGG_Data__8->GetXaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_Data__8->GetXaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_Data__8->GetXaxis()->SetTitleSize(0.05);
   CRInvertLepCut_mGG_Data__8->GetXaxis()->SetTitleOffset(0.95);
   CRInvertLepCut_mGG_Data__8->GetXaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_Data__8->GetYaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_Data__8->GetYaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_Data__8->GetYaxis()->SetTitleSize(0.07);
   CRInvertLepCut_mGG_Data__8->GetYaxis()->SetTitleOffset(0.72);
   CRInvertLepCut_mGG_Data__8->GetYaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_Data__8->GetZaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_Data__8->GetZaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_Data__8->GetZaxis()->SetTitleSize(0.035);
   CRInvertLepCut_mGG_Data__8->GetZaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_Data__8->Draw("E SAME P");
   
   TLegend *leg = new TLegend(0.9,0.5,1,0.89,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("CRInvertLepCut_mGG_Data","Data","lp");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("CRInvertLepCut_mGG_Top","Top","f");

   ci = TColor::GetColor("#993333");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#993333");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("CRInvertLepCut_mGG_Photons","Photons","f");

   ci = TColor::GetColor("#ffcc00");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ffcc00");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("CRInvertLepCut_mGG_VectorBosons","VectorBosons","f");

   ci = TColor::GetColor("#009900");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#009900");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("CRInvertLepCut_mGG_OtherHiggs","OtherHiggs","f");

   ci = TColor::GetColor("#0000ff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("CRInvertLepCut_mGG_ttH+tHW","ttH+tHW","f");

   ci = TColor::GetColor("#ff0000");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("CRInvertLepCut_mGG_tHq","tHq","f");

   ci = TColor::GetColor("#003333");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#003333");
   entry->SetLineColor(ci);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0,0,"");
tex->SetNDC();
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
   
   TPaveText *pt = new TPaveText(0.3846991,0.9342405,0.8551124,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   AText = pt->AddText("Inverted Lepton selection Control Region");
   pt->Draw();
   CRInvertLepCut_mGG_pad1->Modified();
   CRInvertLepCut_mGG_canvas->cd();
  
// ------------>Primitives in pad: CRInvertLepCut_mGG_pad2
   TPad *CRInvertLepCut_mGG_pad2 = new TPad("CRInvertLepCut_mGG_pad2", "CRInvertLepCut_mGG_pad2",0,0,1,0.24);
   CRInvertLepCut_mGG_pad2->Draw();
   CRInvertLepCut_mGG_pad2->cd();
   CRInvertLepCut_mGG_pad2->Range(90,-0.25,190,2.25);
   CRInvertLepCut_mGG_pad2->SetFillColor(0);
   CRInvertLepCut_mGG_pad2->SetBorderMode(0);
   CRInvertLepCut_mGG_pad2->SetBorderSize(2);
   CRInvertLepCut_mGG_pad2->SetFrameBorderMode(0);
   CRInvertLepCut_mGG_pad2->SetFrameBorderMode(0);
   
   TH1F *CRInvertLepCut_mGG_RatioUncert__9 = new TH1F("CRInvertLepCut_mGG_RatioUncert__9","cCRInvertLepCut",8,100,180);
   CRInvertLepCut_mGG_RatioUncert__9->SetBinContent(1,1);
   CRInvertLepCut_mGG_RatioUncert__9->SetBinContent(2,1);
   CRInvertLepCut_mGG_RatioUncert__9->SetBinContent(3,1);
   CRInvertLepCut_mGG_RatioUncert__9->SetBinContent(4,1);
   CRInvertLepCut_mGG_RatioUncert__9->SetBinContent(5,1);
   CRInvertLepCut_mGG_RatioUncert__9->SetBinContent(6,1);
   CRInvertLepCut_mGG_RatioUncert__9->SetBinContent(7,1);
   CRInvertLepCut_mGG_RatioUncert__9->SetBinContent(8,1);
   CRInvertLepCut_mGG_RatioUncert__9->SetBinError(1,0.2648518);
   CRInvertLepCut_mGG_RatioUncert__9->SetBinError(2,0.2996923);
   CRInvertLepCut_mGG_RatioUncert__9->SetBinError(3,0.2821378);
   CRInvertLepCut_mGG_RatioUncert__9->SetBinError(4,0.2260892);
   CRInvertLepCut_mGG_RatioUncert__9->SetBinError(5,0.398043);
   CRInvertLepCut_mGG_RatioUncert__9->SetBinError(6,0.4329528);
   CRInvertLepCut_mGG_RatioUncert__9->SetBinError(7,0.735387);
   CRInvertLepCut_mGG_RatioUncert__9->SetBinError(8,0.4540484);
   CRInvertLepCut_mGG_RatioUncert__9->SetMinimum(0);
   CRInvertLepCut_mGG_RatioUncert__9->SetMaximum(2);
   CRInvertLepCut_mGG_RatioUncert__9->SetEntries(46.2588);
   CRInvertLepCut_mGG_RatioUncert__9->SetDirectory(0);
   CRInvertLepCut_mGG_RatioUncert__9->SetStats(0);
   CRInvertLepCut_mGG_RatioUncert__9->SetFillColor(1);
   CRInvertLepCut_mGG_RatioUncert__9->SetFillStyle(3001);

   ci = TColor::GetColor("#993333");
   CRInvertLepCut_mGG_RatioUncert__9->SetLineColor(ci);
   CRInvertLepCut_mGG_RatioUncert__9->SetLineStyle(2);
   CRInvertLepCut_mGG_RatioUncert__9->SetLineWidth(2);
   CRInvertLepCut_mGG_RatioUncert__9->GetXaxis()->SetBinLabel(1,"");
   CRInvertLepCut_mGG_RatioUncert__9->GetXaxis()->SetBinLabel(2,"");
   CRInvertLepCut_mGG_RatioUncert__9->GetXaxis()->SetBinLabel(3,"");
   CRInvertLepCut_mGG_RatioUncert__9->GetXaxis()->SetBinLabel(4,"");
   CRInvertLepCut_mGG_RatioUncert__9->GetXaxis()->SetBinLabel(5,"");
   CRInvertLepCut_mGG_RatioUncert__9->GetXaxis()->SetBinLabel(6,"");
   CRInvertLepCut_mGG_RatioUncert__9->GetXaxis()->SetBinLabel(7,"");
   CRInvertLepCut_mGG_RatioUncert__9->GetXaxis()->SetBinLabel(8,"");
   CRInvertLepCut_mGG_RatioUncert__9->GetXaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_RatioUncert__9->GetXaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_RatioUncert__9->GetXaxis()->SetTitleSize(0.2);
   CRInvertLepCut_mGG_RatioUncert__9->GetXaxis()->SetTickLength(0.09);
   CRInvertLepCut_mGG_RatioUncert__9->GetXaxis()->SetTitleOffset(0.25);
   CRInvertLepCut_mGG_RatioUncert__9->GetXaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_RatioUncert__9->GetYaxis()->SetTitle("Data / MC");
   CRInvertLepCut_mGG_RatioUncert__9->GetYaxis()->SetNdivisions(509);
   CRInvertLepCut_mGG_RatioUncert__9->GetYaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_RatioUncert__9->GetYaxis()->SetLabelSize(0.1);
   CRInvertLepCut_mGG_RatioUncert__9->GetYaxis()->SetTitleSize(0.18);
   CRInvertLepCut_mGG_RatioUncert__9->GetYaxis()->SetTitleOffset(0.25);
   CRInvertLepCut_mGG_RatioUncert__9->GetYaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_RatioUncert__9->GetZaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_RatioUncert__9->GetZaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_RatioUncert__9->GetZaxis()->SetTitleSize(0.035);
   CRInvertLepCut_mGG_RatioUncert__9->GetZaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_RatioUncert__9->Draw("E2");
   
   TH1F *CRInvertLepCut_mGG_Ratio__10 = new TH1F("CRInvertLepCut_mGG_Ratio__10","cCRInvertLepCut",8,100,180);
   CRInvertLepCut_mGG_Ratio__10->SetBinContent(1,0.8890177);
   CRInvertLepCut_mGG_Ratio__10->SetBinContent(2,0.7960416);
   CRInvertLepCut_mGG_Ratio__10->SetBinContent(3,1.029194);
   CRInvertLepCut_mGG_Ratio__10->SetBinContent(4,1.177337);
   CRInvertLepCut_mGG_Ratio__10->SetBinContent(5,1.463576);
   CRInvertLepCut_mGG_Ratio__10->SetBinContent(6,0.8222132);
   CRInvertLepCut_mGG_Ratio__10->SetBinContent(7,1.107292);
   CRInvertLepCut_mGG_Ratio__10->SetBinContent(8,0.3760546);
   CRInvertLepCut_mGG_Ratio__10->SetBinError(1,0.2202702);
   CRInvertLepCut_mGG_Ratio__10->SetBinError(2,0.248614);
   CRInvertLepCut_mGG_Ratio__10->SetBinError(3,0.285289);
   CRInvertLepCut_mGG_Ratio__10->SetBinError(4,0.3236246);
   CRInvertLepCut_mGG_Ratio__10->SetBinError(5,0.5590127);
   CRInvertLepCut_mGG_Ratio__10->SetBinError(6,0.4456092);
   CRInvertLepCut_mGG_Ratio__10->SetBinError(7,0.6739009);
   CRInvertLepCut_mGG_Ratio__10->SetBinError(8,0.195312);
   CRInvertLepCut_mGG_Ratio__10->SetMinimum(0);
   CRInvertLepCut_mGG_Ratio__10->SetMaximum(2);
   CRInvertLepCut_mGG_Ratio__10->SetEntries(45.15049);
   CRInvertLepCut_mGG_Ratio__10->SetDirectory(0);
   CRInvertLepCut_mGG_Ratio__10->SetStats(0);
   CRInvertLepCut_mGG_Ratio__10->SetFillStyle(3001);
   CRInvertLepCut_mGG_Ratio__10->SetLineWidth(2);
   CRInvertLepCut_mGG_Ratio__10->SetMarkerStyle(20);
   CRInvertLepCut_mGG_Ratio__10->GetXaxis()->SetBinLabel(1,"");
   CRInvertLepCut_mGG_Ratio__10->GetXaxis()->SetBinLabel(2,"");
   CRInvertLepCut_mGG_Ratio__10->GetXaxis()->SetBinLabel(3,"");
   CRInvertLepCut_mGG_Ratio__10->GetXaxis()->SetBinLabel(4,"");
   CRInvertLepCut_mGG_Ratio__10->GetXaxis()->SetBinLabel(5,"");
   CRInvertLepCut_mGG_Ratio__10->GetXaxis()->SetBinLabel(6,"");
   CRInvertLepCut_mGG_Ratio__10->GetXaxis()->SetBinLabel(7,"");
   CRInvertLepCut_mGG_Ratio__10->GetXaxis()->SetBinLabel(8,"");
   CRInvertLepCut_mGG_Ratio__10->GetXaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_Ratio__10->GetXaxis()->SetLabelSize(0);
   CRInvertLepCut_mGG_Ratio__10->GetXaxis()->SetTitleSize(0.2);
   CRInvertLepCut_mGG_Ratio__10->GetXaxis()->SetTickLength(0.09);
   CRInvertLepCut_mGG_Ratio__10->GetXaxis()->SetTitleOffset(0.25);
   CRInvertLepCut_mGG_Ratio__10->GetXaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_Ratio__10->GetYaxis()->SetTitle("Data / MC");
   CRInvertLepCut_mGG_Ratio__10->GetYaxis()->SetNdivisions(509);
   CRInvertLepCut_mGG_Ratio__10->GetYaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_Ratio__10->GetYaxis()->SetLabelSize(0.1);
   CRInvertLepCut_mGG_Ratio__10->GetYaxis()->SetTitleSize(0.18);
   CRInvertLepCut_mGG_Ratio__10->GetYaxis()->SetTitleOffset(0.25);
   CRInvertLepCut_mGG_Ratio__10->GetYaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_Ratio__10->GetZaxis()->SetLabelFont(42);
   CRInvertLepCut_mGG_Ratio__10->GetZaxis()->SetLabelSize(0.035);
   CRInvertLepCut_mGG_Ratio__10->GetZaxis()->SetTitleSize(0.035);
   CRInvertLepCut_mGG_Ratio__10->GetZaxis()->SetTitleFont(42);
   CRInvertLepCut_mGG_Ratio__10->Draw("ep same");
   TLine *line = new TLine(100,1,180,1);
   line->SetLineStyle(7);
   line->SetLineWidth(2);
   line->Draw();
   CRInvertLepCut_mGG_pad2->Modified();
   CRInvertLepCut_mGG_canvas->cd();
   CRInvertLepCut_mGG_canvas->Modified();
   CRInvertLepCut_mGG_canvas->cd();
   CRInvertLepCut_mGG_canvas->SetSelected(CRInvertLepCut_mGG_canvas);
   CRInvertLepCut_mGG_canvas->ToggleToolBar();
}
